baseURL = "/"
theme = "terminal"

[params]
    fullWidthTheme = false
    centerTheme = true
    readmore = "↳"

[languages]
    [languages.en]
        title = "Jackson has a blog"
        [languages.en.params.logo]
            logoText = "Jackson has a blog"

[deployment]
    [[deployment.targets]]
        name = "AWS"
        URL = "s3://jacksontheel.com?region=us-west-2"